#!/bin/bash

# Bongo, Bongo, Bongo I Don't Want to Leave the Mongo
mongod --dbpath /mongo/db --rest --logpath /mongo/log &
# keep trying until server starts 
while ! mongoimport --db eshop --collection products --type json --file /mongo/products.json --jsonArray 2> /dev/null; do sleep 0.2; done

# Hadoop
service ssh start
hadoop namenode -format
start-all.sh
hdfs dfs -mkdir -p /data
hdfs dfs -put /hadoop/products.csv /data/products.csv